sparcs-kaist/new-ara-app

lib/pages/post_view_page.dart, lib/pages/user_view_page.dart, lib/widgets/in_article_web_view.dart
user_view_page.dart에 스크롤 로딩 인디케이터 기능 개발 및 전체적인 리팩토링을 진행하였습니다.
우선 user_view_page.dart의 ListView에 스크롤 로딩 인디케이터 기능이 제대로 동작하지 않아 수정하였습니다.
또한 리팩토링한 부분으로는
1. dio의 try, catch문 수정
2. collection if 도입
3. 빌드 위젯을 함수화하여 분리
4. SvgPicture.asset deprecated된 color 필드 수정
5. 함수 위치 조정
이 있습니다.
=> UserViewPage에 스크롤 로딩 인디케이터 추가

lib/models/article_model.dart, lib/pages/post_write_page.dart
1.  Feat: 자유게시판 익명 기능 구현
2. Fix: 에디터의 내용이 빈 칸일 시 업로드 버튼 비활성화
3. Fix: 메뉴바 오류 수정 (맨 처음 게시물 작성 시 "말머리 없음" -> "말머리를 선택하세요")
=> Feature/post write page/anonymous

lib/pages/free_bulletin_board_page.dart
free_bulletin_page.dart에 다음 페이지 불러올 때 로딩 인디케이터 불러오기
=> Feat(free_bulletin_board_page.dart): 게시물 하단 도달 시 로딩 인디케이터 추가

lib/pages/notification_page.dart, lib/pages/user_page.dart, lib/pages/user_view_page.dart
Fix: scroll indicator 표시 조건을 pixels ">=" maxScrollExtent로 수정함
@sangohkim 이 개발한 파일에 대해서 수정함.
- UserPage, UserViewPage, NotificationPage
=> Scroll indicator 표시 조건 수정 - alvin

lib/pages/post_view_page.dart, lib/utils/post_view_utils.dart, lib/widgets/dialogs.dart
Feat: PostViewPage에 글 삭제 기능 구현(차단 기능은 다른 브랜치에서 구현할 예정)
Design: PostViewPage에서 자신의 글일 경우에 삭제 버튼, 타인의 글일 경우 차단 버튼이 보이도록 함.
PostViewPage의 버튼 디자인의 경우 추후 디자인 TODO 브랜치에서 수정할 예정이라 이번 PR에서는 기능 위주로 리뷰해주시면 될 것 같습니다.
Fix(post_view_page.dart): 프로필 사진 크기 수정 커밋의 경우 본 PR의 목적에는 해당하지 않지만 빠르게 수정가능한 간단한 문제여서 수정하였습니다.
=> PostViewPage 글 삭제 기능 구현

lib/pages/main_navigation_tab_page.dart
바텀 네비게이션 바를 높이 수정을 위해 커스텀 위젯으로 변경하였습니다.
=> Feat(main_navigation_tab_page.dart): 네비게이션 바를 커스텀 위젯으로 변경

lib/models/block_model.dart, lib/models/public_user_model.dart, lib/pages/setting_page.dart, lib/widgets/dialogs.dart
Feat(setting_page.dart): 차단한 유저 목록 표시 기능 구현
=> Feature: 차단된 유저 목록 표시 기능 구현

lib/pages/post_view_page.dart, lib/utils/time_utils.dart
PostViewPage를 figma 디자인과 최대한 유사하도록 변경하였습니다.
코드 및 렌더링 시 overflow 발생 여부를 위주로 리뷰 부탁드립니다.
=> PostViewPage 디자인 피드백 반영

lib/pages/post_write_page.dart
post_write_page.dart에서 입력창 클릭하면 키보드가 보입니다.
이 때 키보드가 내려가게 할 수 있는 버튼을 추가하였습니다.
=> Feat(post_write_page): 키보드 내리는 버튼 추가

lib/models/article_model.dart, lib/models/public_user_model.dart, lib/pages/post_view_page.dart, lib/utils/post_view_utils.dart, lib/widgets/dialogs.dart
=> PostViewPage 차단 기능 구현

ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Info.plist, lib/widgets/in_article_web_view.dart
PostViewPage의 웹뷰 내용을 확대, 축소해서 볼 수 있는 기능을 구현하였습니다.
iOS 실물기기, Android 실물기기에서 정상적으로 작동하는 것을 확인하였습니다.
=> PostViewPage pinch-to-zoom (zoom in, zoom out) 기능 구현

lib/main.dart, lib/pages/main_navigation_tab_page.dart, lib/pages/notification_page.dart, lib/pages/post_view_page.dart, lib/pages/user_page.dart, lib/pages/user_view_page.dart, lib/widgets/loading_indicator.dart
NotificationPage
- 알림 중앙정렬 취소
- 피그마 디자인 반영
PostViewPage
- 피그마 디자인 적용
UserPage
- 리스트뷰 하단 여백 제거
UserViewPage
- 리스트뷰 하단 여백 제거
LoadingIndicator
- iOS에서는 Cupertino 새로고침 아이콘이 나오도록 추가함
전체적으로 iOS인 경우 Cupertino 디자인이 적용되도록 변경함.
시스템 폰트 크기가 변하더라고 앱의 폰트가 영향을 받지 않도록 수정함.
하단 채팅 아이콘 제거
=> v1.0.0 feedback - alvin

lib/pages/main_navigation_tab_page.dart
=> Fix(main_navigation_tab_page.dart): 아이콘 하이라이트 수정

lib/pages/main_navigation_tab_page.dart
빨간색이 터치 가능한 영역
수식으로 계산해서 spaceEvenly를 구현했습니다.
=> Feature(main_navigation_tab_page.dart): 터치 가능한 영역 늘림

ios/Podfile.lock, lib/pages/post_list_show_page.dart
기존 : currentPage가 무한히 증가해 문제
변경 try catch로 감싸고, catch에서 currentPage 1 감소
=> Fix(post_list_show_page.dart): 더 불러올 게시물이 없으면 에러나던 문제 해결

android/app/src/main/AndroidManifest.xml
=> Fix(AndroidManifest.xml): main INTERNET 권한 허용

pubspec.yaml
https://github.com/sparcs-kaist/new-ara-app/releases/edit/untagged-fb461913e4cbdb858bcd
=> Chore: change version to 0.1.2

lib/pages/user_page.dart
기존 : userFetchRes를 페이지 로딩할 때 가져옴으로써 페이지 로딩 속도가 너무 느려짐.
변경 : 코드 삭제함. 유저 정보에 오류가 있을 시 article를 fetch하는 api에서 오류가 날 것이고 try catch로 잡혀짐.
=> Delete(user_page.dart): 유저 정보 조회하는 코드 삭제.

lib/pages/bulletin_search_page.dart
기존 : 검색창에 "아이돌" 입력 시 이상한 결과 창이 뜸.
원인 : onChange 메소드 상 "아이도"에서 "아이돌"입력시 "아","아이","아이돌" 가 value로 들어오는 onChange가 다시 실행됨.
변경 : 현재 검색창의 text(controller.text)와 onChanged의 value랑 같을 때만 setState 실행
=> Fix(buleetin_search_page.dart): 검색 오류 수정

lib/main.dart, lib/models/user_profile_model.dart, lib/pages/main_page.dart, lib/pages/profile_edit_page.dart, lib/pages/user_page.dart, lib/providers/user_provider.dart, lib/utils/create_dio_with_config.dart
기존 : newara dev에만 맞춰져서 게시물들 표시
원인 : newara dev에는 본 서버보다 게시판 갯수가 적어 구구주먹식으로 코딩
변경 : newaredev와 newara에 맞춰져서 게시물들 표시되도록 중간에 새로운 함수 추가
=> Newara 본서버에서도 MainPage에 올바른 게시물이 표시되도록 수정

lib/widgets/pop_up_menu_buttons.dart
채팅 버튼을 주석처리하고 TODO 주석을 추가했습니다.
=> Comment(pop_up_menu_buttons.dart): 채팅 버튼 주석화 및 TODO 추가

lib/pages/post_list_show_page.dart
post_list_show.dart 에 Refresh.adaptive 추가했습니다.
=> PostListShowPage 페이지에 Refresh.adaptive 기능 추가

lib/pages/post_view_page.dart, lib/widgets/post_preview.dart
=> 제목 앞에 parent_topic 빨간 글씨 표시

lib/pages/setting_page.dart, lib/pages/user_page.dart, lib/widgets/dialogs.dart
=> SettingPage 알림 제거

lib/pages/login_page.dart, lib/pages/sparcs_sso_page.dart
한 번 실행해보시고 원하는 기능이 구현이 되었는 지 확인해주세요.
=> Feat: SparcsSSOPage에서 LoginPage로 갈 수 있도록(전 페이지로 갈 수 있도록) 기능 추가

lib/pages/notification_page.dart
알림이 없을 경우 아래와 같이 표시되도록 변경했습니다.
=> '알림이 없습니다' 문구 표시하기

lib/widgets/in_article_web_view.dart
안드로이드 웹뷰 crash 문제 해결했습니다.
Related issue: https://github.com/flutter/flutter/issues/104889
기존에 crash 나던 게시물(터지는 게시판, https://newara.dev.sparcs.org/post/7815?from_view=scrap)로 테스트 해보시면 될 것 같습니다.
https://github.com/sparcs-kaist/new-ara-app/assets/48672097/07df04b2-2795-4ea5-95b1-541204ed0cf2
=> PostViewPage Android webview crash 해결

lib/pages/profile_edit_page.dart
=> ProfileEditPage 닉네임 관련 문구 삽입

lib/utils/profile_image.dart, lib/widgets/dialogs.dart
기존: Image.network를 불러오는 동안 placeholder가 없어 에러가 나고 본서버를 보는 도중에 에러가 많이 발생했었습니다.
변경: placeholder 추가
=> Fix: Image.network _loadAsync 에러 해결

lib/pages/post_write_page.dart
1. 자유 게시판에 익명으로만 올라가던 버그 수정했습니다.
2. html editor 툴바 alignment 디자인 수정했습니다.
=> chore: 익명 기능, 툴바 alignment 수정

lib/pages/bulletin_search_page.dart, lib/pages/post_list_show_page.dart
검색 페이지, 포스트 리스트 페이지에서 항상 리스트 뷰가 스크롤 가능하도록 수정했습니다.
=> Feat: physics 필드를 AlwaysCrollableScrollPhysics()로 변경

lib/constants/url_info.dart
=> Fix: change url to prod

CONTRIBUTING.md
=> CONTRIBUTING.md 릴리즈 방법 설명 추가

lib/pages/inquiry_page.dart, lib/pages/post_write_page.dart
=> PostWritePage 함수 역할 설명 주석 추가

lib/pages/main_page.dart
MainPage에서 다른 페이지에서 돌아올 때 콘텐츠를 새로고침하는 기능을 추가
=> Add process to refresh content on MainPage when returning from another page

lib/pages/bulletin_list_page.dart, lib/pages/post_write_page.dart, lib/pages/terms_and_conditions_page.dart, lib/utils/html_info.dart
=> Fix: noto sans 폰트를 아직 사용하는 곳과 중복으로 선언하는 코드 수정

pubspec.yaml
font가 변경되는 유의미한 디자인 변화라 Minor Version 숫자 증가했습니다.
=> Change-version-to-1.1.0

assets/translations/en.json, assets/translations/ko.json, lib/pages/post_view_page.dart, lib/translations/codegen_loader.g.dart, lib/translations/locale_keys.g.dart
feat/translations/main 에서 영어 지원된 페이지 제외하고 영어지원
=> PostViewPage 등등 영어 추가

assets/translations/ko.json, lib/translations/codegen_loader.g.dart
koName으로 표기되어 있어 에러나던 부분을 ko_name으로 수정함
=> Fix: bulletinSearchPage searchIn ko 수정

lib/pages/post_list_show_page.dart
PostListShowPage에서 로딩바 위치 변경 및 로딩 페이지 제거
- LoadingIndicator displacement 변경 
- isLoading 시 blank box에 LoadingIndicator 제거
외부 페이지 (main_page.dart, notification_page.dart, post_view_page.dart, user_page.dart, user_view_page.dart) 에도 RefreshIndicator.adaptive의 displacement 변경
=> 게시물 페이지에서 Loading Page 제거 & 위치 변경

lib/pages/inquiry_page.dart
padding과 decoration 변경
문의 메시지 box 디자인 변경
padding 추가 및 underline 제거
=> Design(inquiry_page.dart): TextBox 수정

lib/pages/main_page.dart, lib/pages/user_page.dart, lib/pages/user_view_page.dart, lib/utils/cache_function.dart, lib/widgets/dialogs.dart
getApiRes가 완전히 도입되지 못한 부분을 수정함.
=> UserProvider의 getApiRes 미적용 부분 수정

lib/pages/post_list_show_page.dart
#203 마무리
각 페이지에 있는 글의 개수가 10개 이하라면 마지막 페이지 도달 메시지 추가 X
https://github.com/user-attachments/assets/707167d7-231a-4d49-a641-9ff65319de4a
=> feat: decorate last item

lib/utils/html_info.dart
#95 해결
HTML 랜더링 되는 텍스트와 Text로 제공되는 텍스트 사이의 폰트 차이 문제 해결
=> fix: comment HTML issue

.github/workflows/deploy.yml
=> deploy workflow 버그 수정
