lib/pages/post_view_page.dart
lib/pages/profile_edit_page.dart
lib/pages/user_page.dart
lib/pages/user_view_page.dart
lib/utils/profile_image.dart
lib/widgets/dialogs.dart

Add(profile_image.dart): 이미지 null처리 로직 함수화
Fix(post_view_page.dart): 글 작성자 프로필, 댓글 작성자 프로필 이미지 null인 경우 처리
Fix(user_view_page.dart): 사용자 프로필 이미지 null인 경우 처리
Fix(user_page.dart): 사용자 프로필 이미지 null인 경우 처리
Fix(profile_edit_page.dart): 사용자 프로필 이미지 null인 경우 처리
**중간에 에러 처리 방식을 변경하여 커밋이 다소 많은 편인데 Add(profile_image.dart): null처리로직 함수화 커밋(1e87df8)부터 리뷰하셔도 괜찮을 것 같습니다.**
이미지를 로드하기 전 uri를 검사하여 이미지 uri가 null인 경우에 assets/icons/warning.svg를 로드하도록 처리하였습니다.
그리고 uri가 null인 것을 제외한 다른 exception을 처리하기 위하여 Image.network의 errorBuilder를 설정하였습니다.

Null 프로필 처리 로직 적용

---

ios/Runner/Info.plist
lib/utils/post_view_utils.dart

문제상황: IOS에서 파일 다운로드를 할 경우 다운로드가 성공하였음에도 파일을 확인할 수 없는 에러가 발생했었음.
원인: 파일이 기기의 app document에 설치는 제대로 되었으나, file provider가 모든 앱의 파일을 읽을 수 있는 것이 아니라 읽을 수 있게 허용된 앱의 파일만 읽어서 표시하여 다운로드는 되었지만 정작 사용자에게는 보이지 않았던 것
해결방법: Info.plist에 LSSupportsOpeningDocumentsInPlace, UIFileSharingEnabled를 true로 설정하여 해결 가능
- LSSupportsOpeningDocumentsInPlace: IOS 및 third-party file provider 의 파일에 new-ara-app이 접근할 수 있음
- UIFileSharingEnabled: LSSupportsOpeningDocumentsInPlace와 함께 쓰였을 때 file provider가 app document의 모든 문서에 접근할 수 있게 해줌.
iOS simulator에서는 작동을 확인했으나 iOS 실물 기기에서 확인한번 부탁드립니다.

IOS 첨부파일 다운로드 에러 해결

---

lib/constants/url_info.dart
lib/pages/sparcs_sso_page.dart

Feat(sparcs_sso_page.dart): iOS에 대해서 Facebook, Twitter 소셜 로그인을 제거했습니다(앱스토어 심사때문)
Fix(sparcs_sso_page.dart): SPARCS SSO 페이지를 웹뷰로 띄울 때 하단에 '개발팀', '관리자' 기능이 mailto scheme을 사용합니다. 현재 앱에서 mailto scheme 처리가 구현되어 있지 않기 때문에 우선 비활성화해두었습니다.
- 곧 사용자 메시지(ScaffoldMessenger 등등)을 만들게 되면 관련 알림 코드도 작성해두겠습니다(sparcs_sso_page.dart 내에 TODO 주석 처리해놓았습니다)
제거 방법은 client_id, state를 발급받은 상태에서 social_enabled, show_disabled_button 파라미터를 모두 0으로 설정하는 방법으로 구현이 가능합니다.
- [관련 SSO 문서](https://www.notion.so/sparcs/SSO-d9a6a434839e417bbe1185940bf68c55?pvs=4) 및 현 PR의 코드를 통해 자세히 확인하실 수 있습니다.
iOS simulator, Android 실물기기에서 정상작동을 확인하였습니다.

SPARCS SSO Facebook, Twitter 로그인 비활성화 (iOS 한정)

---

lib/utils/slide_routing.dart

CupertinoPageRoute를 이용해서 back swipe 제스처를 인식하도록 하였습니다.
우선 이 기능을 iOS, Android에서 모두 사용할 수 있도록 해두었습니다.
Android에서는 기존의 방식을 유지할 지, back swipe를 사용할 수 있도록 CupertinoPageRoute를 적용할 지 논의가 필요할 것 같습니다.
Android 실물기기, iOS simulator에서 잘 동작하는 것을 확인하였습니다. iOS 실물 기기에서 잘 동작하는지 확인 부탁드립니다.
(만약 이미 밀어서 뒤로가기 개발하신 상태라면 저에게 말씀해주시면 이 PR은 삭제하도록 하겠습니다)

Feature(slide_routing.dart): back swipe 적용하기

---

lib/pages/post_view_page.dart

어제 있었던 머지 이슈로....좋아요, 싫어요 버튼 빌드 함수가 빠져있어서 다시 추가했습니다. 로직은 바뀐게 없고 디자인만 변경되었습니다.

Fix(post_view_page.dart): 좋아요, 싫어요 버튼 다시 추가

---

lib/utils/html_info.dart

웹뷰에서 제대로 렌더링 되지 않던 u, blockquote 태그가 제대로 표시되도록 함.
또한 font를 Noto Sans KR이 적용되도록 하였으며 주요 html 태그에 대한 아라 css를 웹뷰에 적용함.

Fix: webview 오류 태그 수정 및 폰트 설정

---

lib/utils/html_info.dart

code 태그가 제대로 표시되지 않아서 관련 css 설정을 추가함

PostViewPage code 태그 css 추가

---

lib/pages/post_view_page.dart

기존 앱에서는 자신의 글에 대해서는 수정 버튼이 보이게 되어 있었음. 그러나 자신의 글이라도 숨겨져있는 경우 수정 기능이 지원되지 않아 무한로딩이 발생했음.
수정 버튼이 보여지는 조건에 is_hidden=false를 추가하여 해결함.

is_hidden=true일 때 자신의 글 수정 불가능하게 변경

---

lib/pages/post_view_page.dart
lib/pages/user_view_page.dart

현재 아라 정책상, name_type이 1이 아닌 사용자에 대해서는 사용자 정보를 확인할 수 없게 되어있음.
그런데 앱에서 name_type == 2 (익명인 경우)는 잘 필터링했지만 name_type == 4와 같은 다른 경우를 체크하지 못해서 무한로딩이 발생함.
name_type == 1이 아니면 UserViewPage로 가지 않도록 수정하여 해결함.

UserViewPage 무한로딩 해결

---

lib/pages/post_view_page.dart

댓글 닉네임에 오버플로우 처리가 제대로 안되있어서 추가했습니다.
혹시 몰라서 다른 컴포넌트들고 오버플로우 관련 설정 한번씩 확인해보았습니다.

Fix(post_view_page.dart): 댓글 닉네임 maxWidth 수정

---

lib/pages/post_list_show_page.dart
lib/pages/post_view_page.dart
lib/pages/post_write_page.dart
lib/pages/setting_page.dart
lib/pages/user_page.dart

기존: 자식들이 차지하고 있지 않는 화면 상 빈공간에는 gesture가 인식이 안됨
원인: behavior의 속성 때문
변경: behavior의 속성 deferToChild(default) -> translucent

Fix: GestureDectector behavior 속성 변경

---

lib/pages/post_view_page.dart

현재 경험적으로 보았을 때, 아라 서버에서 '<', '>'가 저장되는 방식이 아래 두 가지인 것 같습니다.
1. HTML 태그로 사용되었을 때
- '>', '<'가 문자 그대로 저장됨
2. 그 이외의 경우
- '&lt;', '&gt;'로 인코딩되어 저장됨
따라서 위 두 가지 경우에는 웹뷰로 로드하여 정상적으로 표시되도록 변경하였습니다.

'<', '>' 표시 문제 해결

---

lib/pages/post_view_page.dart

댓글 작성 후 맨 하단으로 움직이는 픽셀 크기 수정했습니다.
댓글 한 줄 기준 72pixels 입니다.
댓글 블럭 사이즈(72pixels)만큼 움직입니다.
<hr>
변경후:
https://github.com/sparcs-kaist/new-ara-app/assets/5186472/aec40dc4-d477-4f56-b360-96f82ec0b627

Fix(post_view_page.dart): fix autoscroll height

---

lib/pages/post_list_show_page.dart
lib/pages/post_write_page.dart

**다음 페이지의 게시물들이 로드 되지 않던 버그 수정**
기존: 게시물 목록 끝까지 갔다가 게시판을 새로고침한 후, 아래로 스크롤을 내리면 다음 페이지의 게시물들이 로드 되지 않던 문제 발생
원인: pageLimitToReload( 다시 어디까지 로딩되는 페이지)를 지정하고, 현재 페이지(currentPage)를 초기화 안함.
초기화를 안하면 currentPage가 (최대 페이지 +1) 이라 올바른 페이지가 로딩이 안됨.
변경: pageLimitToReload 사용 시 pageLimitToReload를 maxPage로 변경

PostListShowPage 게시판 리프레쉬 후 올바른 다음 페이지 게시물들이 불러와지지 않던 버그 수정

---

lib/pages/post_view_page.dart
lib/pages/post_write_page.dart
lib/pages/setting_page.dart
lib/utils/handle_name.dart
lib/widgets/post_preview.dart

'익명', '글쓴이'에 대해 로케일을 적용했습니다.
또한 설정 페이지, 이용약관 페이지 내비게이션할 때 로케일 적용이 곧바로 되도록 setState 추가했습니다.

익명글에서 작성자명이 '익명', '글쓴이'일 때 로케일 적용

---

lib/utils/time_utils.dart

"39분 전"과 같이 "~분 전" 표현이 "days ago"로 번역되어 있어 "minutes ago"로 수정함.

Fix: day를 minute으로 변경

---

lib/pages/notification_page.dart

항상 '오늘'로 표시되는 것이 아니라 알림의 날짜를 확인하고 실제로 오늘과 같을 시에만 오늘로 표시되도록 변경.

최상단 알림이 항상 '오늘'로 표시되는 버그 수정

---

lib/pages/post_list_show_page.dart

PostListShowPage의 전체 LoadingIndicator가 페이지를 처음 로드했을 때만 한정하여 보이도록 함
post_list_show_page.dart 파일 내부의 일부 코드 변경
- RefreshIndicator() 내부 로직
- build() 메서드 내부
PostListShowPage를 에뮬레이터 또는 실물기기 환경에서 로드하여 확인가능.
#186 
build() 내부의 body에서 삼항연산자 제거.
없음.

PostListShowPage 전체 LoadingIndicator 일부 추가

---

lib/pages/main_page.dart

MainPage의 RefreshIndicator displacement를 제거함.
RefreshIndicator() 위젯의 displacement 필드값을 0으로 변경.

Feat(main_page.dart): Chagne displacement of RefreshIndicator to zero

---

lib/pages/post_list_show_page.dart
lib/utils/with_school.dart

기존에 웹에서는 제공되는 기능이었던 게시판별 말머리 필터 기능을 앱에서 제공하기 위한 PR
PostListShowPage를 통해 게시판에 접속할 때마다 게시판에 해당하는 말머리가 있는 경우 필터링 버튼이 화면에 표시됨
말머리필터 버튼을 누를 때마다 PostListShowPage의 apiUrl에 적절한 query string parameter를 추가하여 리로드하는 방식으로 구현함
#196 
post_list_show_page.dart에서 필터링 관련 코드만 지우면 가능
디자인 피드백 환영합니다....

PostListShowPage 말머리 필터 추가

---

assets/translations/en.json
assets/translations/ko.json
lib/pages/post_write_page.dart
lib/translations/codegen_loader.g.dart
lib/translations/locale_keys.g.dart
lib/widgets/dialogs.dart

게시글 작성 페이지에서 '나가기 버튼'을 누를 때 2차적으로 확인하도록 함
- 나가기 확인 dialog 추가 (글/제목을 적었을 때에만)
- 언어에 맞게 번역
- 고유의 뒤로 돌아가기 (android/ios 모두) 버튼을 누를 때 별도로 처리 (WillPopScope)
- dialogs.dart에 ExitConfirmDialog를 추가 (DeleteDialog와 유사)
- post_write_page.dart의 AppBar에 연동
- 이 때, 제목/글이 있는지 확인
- PopScope로 별도 처리 (os 자체의 돌아가기 버튼 / slide 등)
- 게시물 작성 페이지에서 나갈 시, 확인 dialog 출력
- 
현재 flutter 버전에서 사용되는 WillPopScope가 deprecated됨, 최신 버전에서는 PopScope 사용 권장

PostWritePage에 나가기 확인 dialog 추가

---

assets/translations/en.json
assets/translations/ko.json
lib/pages/post_write_page.dart
lib/translations/codegen_loader.g.dart
lib/translations/locale_keys.g.dart
lib/widgets/dialogs.dart

캐싱 기능 추가
ExitConfirmDialog에서 save 선택시 입력한 내용이 캐싱됨
- 글 수정 시 : /cache/${previousArticle.id}에 저장
- 글 새로 작성시 : /cache/${userID} 에 저장됨
- 작성 화면에서 onTapConfirm시 저장되어 있던 cache 삭제
https://github.com/user-attachments/assets/71164593-5c6d-41d5-98e6-27cc0389493d

[Feature] caching for post write page

---

assets/translations/en.json
assets/translations/ko.json
lib/pages/post_write_page.dart
lib/translations/codegen_loader.g.dart
lib/translations/locale_keys.g.dart
lib/widgets/dialogs.dart

postWritePage에 '임시 저장하기' 기능 추가
- postWritePage에서 나가기 확인 dialog상 '임시 저장' 버튼 추가
- cache_functions를 활용해 글 제목, 내용, 게시판 등 cache에 저장
- 이후 첫 로딩 시 캐시 여부 확인
- cache_functions를 통해 SharedPreferences에 저장
- dialog에서 '나가기'를 누르면 cache clear
- '임시 저장'을 누를 시 cache에 저장
- 이후 postWritePage 접속 시마다 확인
- postWritePage에서 나가도 내용을 임시로 저장할 수 있음

PostWritePage 내용 임시 저장(tempSave)

---

android/app/build.gradle
lib/pages/post_write_page.dart
pubspec.lock
pubspec.yaml

1. PostWritePage에서 첨부파일에 대한 request url을 정상적으로 복구함
2. Android Target API 버전을 33에서 34로 상향
3. 사용하지 않는 패키지인 flutter_local_notification을 제거함
post_write_page.dart, build.gradle 수정함
dev로 머지한 후 PostWritePage 관련 다른 기능들에서 발생하던 에러가 여전히 나타나는지 확인해보아야함.
Flutter 버전을 3.22 정도로 상향시키는 작업이 필요할듯(점점 iOS, Android 모두 플러터 3.13이 타겟팅하는 버전대와는 멀어지는 현상)

main으로 push한 수정사항을 dev에도 반영

---

lib/pages/post_write_page.dart
lib/utils/cache_function.dart

Cache 저장 및 불러오기의 속도를 대폭 증가시킴.
- PostWritePage 로딩 속도 대폭 상승
- 기존의 caching 지연 원인 : cache는 SharedPreferences에서 잘 호출되었으나, 업데이트하는 과정에서 _isLoading=false가 늦게 호출 (updateStateWithFetchedOrCachedData 완료 이후)되면서 로딩화면이 계속됨.
- _getBoardList, _getCachedContents,  (임시 저장, 게시판 목록)을 순서대로 불러와 최종적으로 _getBoardList의 업데이트에 따라 setState가 호출되도록 변경
- 또한 _isLoading=false 를 setState() 내부에 통합시킴으로써 바로 화면이 build되도록 변경.
- '임시 저장' 기능의 api 주소를 변경하고 '확인 / OnTapConfirm' 시 리셋하도록 (removeApiCache) 변경.

Caching 속도 최적화 및 임시 저장 수정
